### ISSUE TITLE
Multiple Countries

### ISSUE THREAD

**Issue by milandzuris** [b0mbays/google_trends#2]
Add Multiple countries

**Comment by b0mbays** [comment]
Hi @milandzuris, the supported countries are listed [here](https://trends.google.com/trends/trendingsearches/daily?geo=GB&hl=en-GB)

**Comment by milandzuris** [comment]
> Hi @milandzuris, the supported countries are listed [here](https://trends.google.com/trends/trendingsearches/daily?geo=GB&hl=en-GB)

Multiple sensors

**Comment by b0mbays** [comment]
Anything more you need with here? Thanks!
