### ISSUE TITLE
Missing google logo in integrations page

### ISSUE THREAD

**Issue by brewston** [b0mbays/google_trends#3]
This is a bit trivial, can't believe I'm asking for it -LOL

Would it be possible to get a google logo added that shows up in the integration page ?

(I'll take a look at existing integration to see if I can figure out where the .png file would be placed)

Thanks

**Comment by brewston** [comment]
Interesting, the logo is not in the integration repo itself - its in https://github.com/home-assistant/brands

**Comment by brewston** [comment]
https://imgur.com/a/zWEwpsm - prepared 2 image files. If you'd prefer me to create the PR for them, LMK.

**Comment by b0mbays** [comment]
Thanks alot for sorting out the icons! I never got round to doing it. 

I have raised a PR here for the branding:

https://github.com/home-assistant/brands/pull/4449

**Comment by b0mbays** [comment]
This has now been merged! Thanks again @brewston 👍
